nt = int(input('Digite um número para ver a tabuada: '))
print('-' * 12)
print('{} x {:2} = {}'.format(nt, 1, (nt*1)))
print('{} x {:2} = {}'.format(nt, 2, (nt*2)))
print('{} x {:2} = {}'.format(nt, 3, (nt*3)))
print('{} x {:2} = {}'.format(nt, 4, (nt*4)))
print('{} x {:2} = {}'.format(nt, 5, (nt*5)))
print('{} x {:2} = {}'.format(nt, 6, (nt*6)))
print('{} x {:2} = {}'.format(nt, 7, (nt*7)))
print('{} x {:2} = {}'.format(nt, 8, (nt*8)))
print('{} x {:2} = {}'.format(nt, 9, (nt*9)))
print('{} x {:2} = {}'.format(nt, 10, (nt*10)))
print('-' * 12)
